music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    #/music/
    url(r'^$',views.index, name='index'),

    #/music/71/
    url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail'),

    #/music/71/favorite
    url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite,name='favorite')
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from __future__ import unicode_literals

from django.db import models

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title+" - "+ self.artist

## a song is a part of an album
class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404

from .models import Album, Song


def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums':all_albums})

def detail(request, album_id):
    album = get_object_or_404(Album,pk=album_id)
    return render(request,'music/details.html', {'album':album} )

def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except (KeyError, Song.DoesNotExist ):
        return render(request, 'music/details.html', {
            'album':album,
            'error_message': "You did not select a vlid song",
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request,'music/details.html', {'album':album} )

music/templates/music/contacts_app.html
<!DOCTYPE html>
<html>
<head>
	<title>Simple Contacts storing application</title>
</head>
<body>
	<p><strong>Simple Contacts storing App</strong></p>
	<div>
		First Name : <input type="text" id ="first_name">
		Last Name : <input type="text" id="last_name">
		Email : <input type="text" id="email">
		<br><br>
		<input type="button" name="submit" value="Add Contact" onclick="addContent()">
	</div>

	<br>
	
	<div>
		<p><strong>Available Contacts:</strong></p>
		<div id ="info">
			
		</div>
		<!--table id="info">
			<tr>
				<th> # </th>
			    <th>First Name</th>
			    <th>Last Name</th>
			    <th>Email</th>
  			</tr>
  			<!--tr>
  				<td>1</td>
			    <td>First Name</td>
			    <td>Last Name</td>
			    <td>Email</td>
  			</tr-->
		</table>
	</div>
	<script>
		app_data = [["John","Doe","johndoe@example.com"],["John","Doe","johndoe@example.com"],["John","Doe","johndoe@example.com"],["John","Doe","johndoe@example.com"]];
		

		function refreshTable(){
			var table ='<table> <tr><th> # </th> <th>First Name</th> <th>Last Name</th> <th>Email</th></tr>';
			for(var i=0; i<app_data.length; i++){
				table += '<tr><td>'+(i+1)+'</td><td>'+app_data[i][0]+'</td><td>'+ app_data[i][1] +'</td><td>'+app_data[i][2]+'</td></tr>';
			}
			table += '</table>'
			document.getElementById("info").innerHTML = table;
		}

		function addContent(){
			var fname = document.getElementById("first_name").value;
			var lname = document.getElementById("last_name").value;
			var email = document.getElementById("email").value;
			
			if(fname=="" || lname=="" || email=="")
				return alert("all fields must be filled !!!!");
			
			app_data[app_data.length] = [fname, lname, email];
			refreshTable();
		}

		refreshTable();
	</script>
</body>
</html>

music/templates/music/details.html
<img src="{{ album.album_logo}}">

<h1>{{album.album_title}}</h1>
<h3>{{album.artist}}</h3>

{% if error_message %}
    <p><strong>{{error_message}}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}
            {% if song.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png" />
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

music/templates/music/index.html
{% if all_albums %}
<h4>all available albums</h4>
<ul>
    {% for album in all_albums %}
    <li><a href="{% url 'music:detail' album.id %}">{{album.album_title}}</a></li>
    {% endfor %}
</ul>
{% else %}
<h4>sorry no album available</h4>
{% endif %}